const ALGORITHM_TYPE = {
  CEASAR: 1,
  VIGENERE: 2,
};

const CONVERT_TYPE = {
  ENCODE: 1,
  DECODE: 2,
};

const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

export { ALGORITHM_TYPE, CONVERT_TYPE, ALPHABET };
